apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "eks-nvme-ssd-provisioner.fullname" . }}
spec:
  podSelector:
    matchLabels:
      {{- include "eks-nvme-ssd-provisioner.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
